### ISSUE TITLE
ggplot2 3.0.0?

### ISSUE THREAD

**Issue by bfgray3** [AFIT-R/KraljicMatrix#6]
Hi all.  I have a little bit of free time coming up and was wondering if you think it might be useful for me to write a pull request incorporating ggplot2 3.0.0 (tidyeval) into this package.  Please let me know your thoughts.

**Comment by bradleyboehmke** [comment]
Hey @bfgray3, hope life is well. Sorry for the delayed response.  So yes, you could definitely a PR to incorporate ggplot 3.0.0.  However, we are not actively expanding this package so I try to limit my efforts to provide backward compatibility.  If you want to have a bigger impact, @bgreenwell and I could use some help with the [`vip` package](https://koalaverse.github.io/vip/index.html). 

`vip` was named one of the top 40 new pkgs for this year and we're trying to quickly expand it.  There are some great issues that need attention but Brandon and I time constrained.  Would love to have you contribute.

**Comment by bfgray3** [comment]
Sounds good.  I have a little bit of time before school starts for the fall so I'll see what I can do before then.  Congratulations on writing one of the top new packages!
